package com.andys8.kidsviewer.data

import android.content.Context
import android.util.Log
import androidx.core.net.toUri
import java.io.IOException

private const val TAG = "PictureLibrary"
private const val PICTURE_DIRECTORY = "pictures"
private const val PICTURE_INDEX = "$PICTURE_DIRECTORY/index.txt"

/** Every index line is "<file> <RRGGBB>". Anything shorter or longer is not one. */
private const val INDEX_FIELDS = 2

/** The backdrop is drawn behind the picture, never blended with it, so it is always opaque. */
private const val OPAQUE = 0xFF000000.toInt()

/**
 * The pictures bundled with the app: animals, things that go, food, toys. They are the other
 * thing the viewer can show, for a child who has run out of interest in the camera roll -- and
 * they work on a phone where photo access was never granted, because nothing here asks for one.
 *
 * The files and their backdrop colours are generated by tools/pictures/build-pictures.py, which
 * also writes the index read here. Adding a picture means re-running that script, nothing else.
 */
object PictureLibrary {

    /**
     * Read the index and hand back the pictures in a fresh random order. Shuffling on every read,
     * rather than once at startup, is what makes each visit to picture mode a different sequence.
     *
     * The index is a few kilobytes of names, with no image decoding involved, so reading it on
     * the calling thread costs nothing worth moving off it.
     */
    fun load(context: Context): List<MediaItem> {
        val lines = try {
            context.assets.open(PICTURE_INDEX).bufferedReader().use { it.readLines() }
        } catch (e: IOException) {
            // A viewer with no pictures is still a working viewer, so fail quietly to empty
            // rather than taking the app down over a missing asset.
            Log.w(TAG, "Cannot read $PICTURE_INDEX", e)
            return emptyList()
        }

        return lines.mapIndexedNotNull(::parse).shuffled()
    }

    /** Comments, blanks and anything malformed are skipped: one bad line is not worth a crash. */
    private fun parse(index: Int, line: String): MediaItem? {
        val trimmed = line.trim()
        if (trimmed.isEmpty() || trimmed.startsWith("#")) return null

        val fields = trimmed.split(" ")
        if (fields.size != INDEX_FIELDS) return null
        val backdrop = fields[1].toIntOrNull(radix = 16) ?: return null

        return MediaItem(
            // The line number doubles as the pager's key. It only has to be unique within this
            // list: the two sources are never on screen at the same time.
            id = index.toLong(),
            uri = "file:///android_asset/$PICTURE_DIRECTORY/${fields[0]}".toUri(),
            isVideo = false,
            dateAdded = 0L,
            backdropColor = OPAQUE or backdrop
        )
    }
}
